"""MATLAB cross-validation: Python (c, V) must match MATLAB CertRNN to ~1e-10.

Fixtures generated by tests/matlab/gen_fixtures.m using the MATLAB
reference engine. Both engines append fresh predicates at the END of V,
so column orderings match for single-frame inputs where pred_ids share
a prefix. This test is a tight numerical-identity check, not just a
soundness check; if either engine drifts, we see it here.

Skip behavior: tests skip cleanly when the fixtures directory is empty
(e.g., fresh checkout without MATLAB available). Regenerate with:
    matlab -batch "cd('tests/matlab'); gen_fixtures"
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

from cert_rnn import Zono
from cert_rnn.lstm import lstm_step
from cert_rnn.rnn import rnn_step
from cert_rnn.transformers import (
    bilinear_sigmoid_identity,
    bilinear_sigmoid_tanh,
    sigmoid_zono,
    tanh_zono,
)

FIX_DIR = Path(__file__).parent / "matlab" / "fixtures"
ATOL = 1e-10


def _have(name):
    return (FIX_DIR / f"{name}.mat").exists()


def _load(name):
    return scipy.io.loadmat(str(FIX_DIR / f"{name}.mat"))


def _as_1d(x):
    return np.asarray(x, dtype=np.float64).reshape(-1)


def _as_2d(x):
    a = np.asarray(x, dtype=np.float64)
    return a.reshape(a.shape[0], -1) if a.ndim >= 2 else a.reshape(-1, 1)


pytestmark = pytest.mark.skipif(
    not FIX_DIR.exists() or not any(FIX_DIR.iterdir()),
    reason="MATLAB fixtures missing; run tests/matlab/gen_fixtures.m",
)


def _unary_case(name, transformer):
    data = _load(name)
    c_in = _as_1d(data["c_in"])
    V_in = _as_2d(data["V_in"])
    p = V_in.shape[1]
    z_in = Zono(c_in, V_in, tuple(range(p)))
    z_out = transformer(z_in)
    assert z_out.c.shape == _as_1d(data["c_out"]).shape
    np.testing.assert_allclose(z_out.c, _as_1d(data["c_out"]), atol=ATOL)
    np.testing.assert_allclose(z_out.V, _as_2d(data["V_out"]), atol=ATOL)


@pytest.mark.parametrize(
    "name",
    [
        "tanh_1d_pos",
        "tanh_1d_wide",
        "tanh_1d_saturated",
        "tanh_2d_shared",
    ],
)
def test_matlab_tanh(name):
    _unary_case(name, tanh_zono)


@pytest.mark.parametrize(
    "name",
    [
        "sigmoid_1d_pos",
        "sigmoid_1d_wide",
        "sigmoid_2d_shared",
    ],
)
def test_matlab_sigmoid(name):
    _unary_case(name, sigmoid_zono)


def _binary_case(name, transformer):
    data = _load(name)
    x_c = _as_1d(data["x_c"])
    x_V = _as_2d(data["x_V"])
    y_c = _as_1d(data["y_c"])
    y_V = _as_2d(data["y_V"])
    assert x_V.shape[1] == y_V.shape[1], "fixture must use shared preds"
    ids = tuple(range(x_V.shape[1]))
    z_x = Zono(x_c, x_V, ids)
    z_y = Zono(y_c, y_V, ids)
    z_out = transformer(z_x, z_y)
    np.testing.assert_allclose(z_out.c, _as_1d(data["c_out"]), atol=ATOL)
    np.testing.assert_allclose(z_out.V, _as_2d(data["V_out"]), atol=ATOL)


@pytest.mark.parametrize(
    "name",
    ["sigid_1d_C1", "sigid_1d_C2", "sigid_1d_C3", "sigid_1d_asym"],
)
def test_matlab_bilinear_sigid(name):
    _binary_case(name, bilinear_sigmoid_identity)


@pytest.mark.parametrize(
    "name",
    [
        "sigtanh_1d_pos",
        "sigtanh_1d_neg",
        "sigtanh_1d_mixed",
        "sigtanh_1d_wide",
        "sigtanh_1d_asym",
    ],
)
def test_matlab_bilinear_sigtanh(name):
    _binary_case(name, bilinear_sigmoid_tanh)


def _lstm_step_case(name):
    data = _load(name)
    D = int(data["D"].item())
    H = int(data["H"].item())
    T = int(data["T"].item()) if "T" in data else 1
    W_in = _as_2d(data["W_in"])
    W_rec = _as_2d(data["W_rec"])
    b = _as_1d(data["b"])
    x_c = _as_1d(data["x_c"])
    x_V = _as_2d(data["x_V"])

    z_x = Zono(x_c, x_V, tuple(range(x_V.shape[1])))
    z_h = Zono.point(np.zeros(H))
    z_c = Zono.point(np.zeros(H))
    for _ in range(T):
        z_h, z_c = lstm_step(z_x, z_h, z_c, W_in, W_rec, b)

    np.testing.assert_allclose(z_h.c, _as_1d(data["h_c"]), atol=ATOL)
    np.testing.assert_allclose(z_h.V, _as_2d(data["h_V"]), atol=ATOL)
    np.testing.assert_allclose(z_c.c, _as_1d(data["c_c"]), atol=ATOL)
    np.testing.assert_allclose(z_c.V, _as_2d(data["c_V"]), atol=ATOL)


def test_matlab_lstm_step_1step():
    _lstm_step_case("lstm_step_1step")


def test_matlab_lstm_step_3step():
    _lstm_step_case("lstm_step_3step")


def test_matlab_rnn_step_5step():
    data = _load("rnn_step_5step")
    H = int(data["H"].item())
    T = int(data["T"].item())
    W_in = _as_2d(data["W_in"])
    W_rec = _as_2d(data["W_rec"])
    b = _as_1d(data["b"])
    x_c = _as_1d(data["x_c"])
    x_V = _as_2d(data["x_V"])
    z_x = Zono(x_c, x_V, tuple(range(x_V.shape[1])))
    z_h = Zono.point(np.zeros(H))
    for _ in range(T):
        z_h = rnn_step(z_x, z_h, W_in, W_rec, b)
    np.testing.assert_allclose(z_h.c, _as_1d(data["h_c"]), atol=ATOL)
    np.testing.assert_allclose(z_h.V, _as_2d(data["h_V"]), atol=ATOL)
